layout_spectrum: 0.11835335334762931
typography_spectrum: 0.928116399096325
color:
  brandStrength: 0.9744673268869519
  lightness: 0.7112090706359595
  saturation: 0.1481907763518393
  rhythmicContrast: 0.846821601036936
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/554d5373-cd6d-4c82-a81f-526dd30235ad.png
name: Striving
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/987aded7-b82d-4f7c-ab0d-18b2b4c74a2f.png
title: Striving
description: Better life and stronger performance
