description: Better life and stronger performance
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/554d5373-cd6d-4c82-a81f-526dd30235ad.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.1183533533476293
color:
  saturation: 0.6454315783921629
  brandStrength: 0.6984498489182442
  rhythmicContrast: 0.167497499845922
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  lightness: 0.1353035205975175
title: Striving
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/987aded7-b82d-4f7c-ab0d-18b2b4c74a2f.png
typography_spectrum: 0.9165673127863556
name: Striving
